# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pebble.protos import agent_pb2 as pebble_dot_protos_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pebble/protos/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/pebble.AgentService/GetStatus',
                request_serializer=pebble_dot_protos_dot_agent__pb2.Empty.SerializeToString,
                response_deserializer=pebble_dot_protos_dot_agent__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ProcessAction = channel.unary_unary(
                '/pebble.AgentService/ProcessAction',
                request_serializer=pebble_dot_protos_dot_agent__pb2.ActionRequest.SerializeToString,
                response_deserializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.Listen = channel.unary_unary(
                '/pebble.AgentService/Listen',
                request_serializer=pebble_dot_protos_dot_agent__pb2.AudioRequest.SerializeToString,
                response_deserializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ViewImage = channel.unary_unary(
                '/pebble.AgentService/ViewImage',
                request_serializer=pebble_dot_protos_dot_agent__pb2.ImageRequest.SerializeToString,
                response_deserializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ViewVideo = channel.unary_unary(
                '/pebble.AgentService/ViewVideo',
                request_serializer=pebble_dot_protos_dot_agent__pb2.VideoRequest.SerializeToString,
                response_deserializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=pebble_dot_protos_dot_agent__pb2.Empty.FromString,
                    response_serializer=pebble_dot_protos_dot_agent__pb2.StatusResponse.SerializeToString,
            ),
            'ProcessAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAction,
                    request_deserializer=pebble_dot_protos_dot_agent__pb2.ActionRequest.FromString,
                    response_serializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.SerializeToString,
            ),
            'Listen': grpc.unary_unary_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=pebble_dot_protos_dot_agent__pb2.AudioRequest.FromString,
                    response_serializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.SerializeToString,
            ),
            'ViewImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewImage,
                    request_deserializer=pebble_dot_protos_dot_agent__pb2.ImageRequest.FromString,
                    response_serializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.SerializeToString,
            ),
            'ViewVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewVideo,
                    request_deserializer=pebble_dot_protos_dot_agent__pb2.VideoRequest.FromString,
                    response_serializer=pebble_dot_protos_dot_agent__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pebble.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pebble.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pebble.AgentService/GetStatus',
            pebble_dot_protos_dot_agent__pb2.Empty.SerializeToString,
            pebble_dot_protos_dot_agent__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pebble.AgentService/ProcessAction',
            pebble_dot_protos_dot_agent__pb2.ActionRequest.SerializeToString,
            pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pebble.AgentService/Listen',
            pebble_dot_protos_dot_agent__pb2.AudioRequest.SerializeToString,
            pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pebble.AgentService/ViewImage',
            pebble_dot_protos_dot_agent__pb2.ImageRequest.SerializeToString,
            pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pebble.AgentService/ViewVideo',
            pebble_dot_protos_dot_agent__pb2.VideoRequest.SerializeToString,
            pebble_dot_protos_dot_agent__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
