"""Add foreign key constraint from tasks to contexts

Revision ID: ef0d61440935
Revises: 20251207_0001
Create Date: 2025-12-07 09:05:30.624449+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef0d61440935"
down_revision: Union[str, None] = "20251207_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_contexts_created_at"), table_name="contexts")
    op.create_index("idx_contexts_created_at", "contexts", ["created_at"], unique=False)
    op.drop_index(op.f("idx_contexts_updated_at"), table_name="contexts")
    op.create_index("idx_contexts_updated_at", "contexts", ["updated_at"], unique=False)
    op.drop_index(op.f("idx_task_feedback_created_at"), table_name="task_feedback")
    op.create_index(
        "idx_task_feedback_created_at", "task_feedback", ["created_at"], unique=False
    )
    op.drop_index(op.f("idx_tasks_created_at"), table_name="tasks")
    op.create_index("idx_tasks_created_at", "tasks", ["created_at"], unique=False)
    op.drop_index(op.f("idx_tasks_updated_at"), table_name="tasks")
    op.create_index("idx_tasks_updated_at", "tasks", ["updated_at"], unique=False)
    op.create_foreign_key(
        None, "tasks", "contexts", ["context_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index("idx_tasks_updated_at", table_name="tasks")
    op.create_index(
        op.f("idx_tasks_updated_at"),
        "tasks",
        [sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.drop_index("idx_tasks_created_at", table_name="tasks")
    op.create_index(
        op.f("idx_tasks_created_at"),
        "tasks",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index("idx_task_feedback_created_at", table_name="task_feedback")
    op.create_index(
        op.f("idx_task_feedback_created_at"),
        "task_feedback",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index("idx_contexts_updated_at", table_name="contexts")
    op.create_index(
        op.f("idx_contexts_updated_at"),
        "contexts",
        [sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.drop_index("idx_contexts_created_at", table_name="contexts")
    op.create_index(
        op.f("idx_contexts_created_at"),
        "contexts",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
