from typing import Any

class Compute:
    box: Any

    def __init__(self, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> "Compute": ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> bool | None: ...
